import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Layout from "@/components/layout/Layout";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const Roca = localFont({
  src: "./fonts/RocaRegular.ttf",
  variable: "--font-roca",
  weight: "100 900",
});

const RocaLight = localFont({
  src: "./fonts/RocaLight.ttf",
  variable: "--font-roca-light",
  weight: "100 900",
});

const RocaBold = localFont({
  src: "./fonts/RocaBold.ttf",
  variable: "--font-roca-bold",
  weight: "100 900",
});

const Felix = localFont({
  src: "./fonts/FellixTRIAL-Regular.woff",
  variable: "--font-felix",
  weight: "100 900",
});

const FelixLight = localFont({
  src: "./fonts/FellixTRIAL-Medium.woff",
  variable: "--font-felix-light",
  weight: "100 900",
});

const FelixBold = localFont({
  src: "./fonts/FellixTRIAL-Bold.woff",
  variable: "--font-felix-bold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Roca.variable} ${Felix.variable} ${RocaLight.variable} ${RocaBold.variable} ${FelixLight.variable} ${FelixBold.variable} antialiased`}
      >
          <Layout>
            {children}
          </Layout>
      </body>
    </html>
  );
}
